import json
import re
from typing import Dict, Any, List, Callable
from services.booking_service import BookingService
from services.handoff_service import HandoffService

# Canonical Tool Schemas — each entry is a platform-neutral tool definition understood
# by all three adapters (Mock, Gemini, Groq). Changes here are the single source of truth.
CANONICAL_TOOLS = [
    {
        "name": "get_clinic_info",
        "description": "Get general information about the polyclinic including address, phone number, operating hours, and policies.",
        "parameters": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "get_services",
        "description": "Get the list of medical treatments, consultation services, descriptions, durations, and pricing offered by a specific doctor.",
        "parameters": {
            "type": "object",
            "properties": {
                "doctor_id": {
                    "type": "integer",
                    "description": "ID of the doctor whose services to retrieve"
                }
            },
            "required": ["doctor_id"]
        }
    },
    {
        "name": "get_doctors",
        "description": "Get the complete list of practicing doctors at the clinic with their specializations, working days, and working hours. ALWAYS call this when the customer asks about doctors, doctor names, specializations, or who works at the clinic, even if they also mention wanting an appointment.",
        "parameters": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "check_availability",
        "description": "Check real-time available appointment slots for a specific date and optional doctor or service. ONLY call this tool when an EXPLICIT date (e.g. 'tomorrow', '2026-08-25', or a date stored in context) is provided by the customer. NEVER call this tool if no date is known.",
        "parameters": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "description": "Explicit date in YYYY-MM-DD format for checking availability"
                },
                "doctor_id": {
                    "type": "integer",
                    "description": "Optional ID of the preferred doctor"
                },
                "service_id": {
                    "type": "integer",
                    "description": "Optional ID of the medical service"
                }
            },
            "required": ["date"]
        }
    },
    {
        "name": "book_appointment",
        "description": "Book a confirmed appointment after validating slot availability and collecting patient details.",
        "parameters": {
            "type": "object",
            "properties": {
                "customer_name": {
                    "type": "string",
                    "description": "Full name of the patient/customer"
                },
                "customer_phone": {
                    "type": "string",
                    "description": "Contact phone number of the patient"
                },
                "doctor_id": {
                    "type": "integer",
                    "description": "ID of the doctor"
                },
                "service_id": {
                    "type": "integer",
                    "description": "ID of the medical service"
                },
                "appointment_date": {
                    "type": "string",
                    "description": "Appointment date in YYYY-MM-DD format"
                },
                "appointment_time": {
                    "type": "string",
                    "description": "Appointment time slot in HH:MM format (e.g. 10:00, 14:30)"
                },
                "notes": {
                    "type": "string",
                    "description": "Optional additional patient notes or concerns"
                },
                "idempotency_key": {
                    "type": "string",
                    "description": "Unique key to prevent duplicate bookings on retries. Auto-generated by the agent — do not ask the customer for this."
                }
            },
            "required": ["customer_name", "customer_phone", "doctor_id", "service_id", "appointment_date", "appointment_time"]
        }
    },
    {
        "name": "get_appointment_details",
        "description": "Look up and check the real-time status and details of a customer's appointments (confirmed, cancelled, or rescheduled) from the clinic database. ALWAYS call this tool when the customer asks about their booking details, whether their appointment was cancelled or confirmed, or asks to check their existing appointment.",
        "parameters": {
            "type": "object",
            "properties": {
                "appointment_id": {
                    "type": "integer",
                    "description": "Optional ID of the appointment to look up"
                },
                "customer_phone": {
                    "type": "string",
                    "description": "Optional contact phone number of the customer"
                }
            },
            "required": []
        }
    },
    {
        "name": "cancel_appointment",
        "description": "Cancel an existing booked appointment.",
        "parameters": {
            "type": "object",
            "properties": {
                "appointment_id": {
                    "type": "integer",
                    "description": "ID of the appointment to cancel"
                },
                "reason": {
                    "type": "string",
                    "description": "Optional reason for cancellation"
                }
            },
            "required": ["appointment_id"]
        }
    },
    {
        "name": "reschedule_appointment",
        "description": "Reschedule an existing appointment to a new date and time slot, optionally changing doctor or service.",
        "parameters": {
            "type": "object",
            "properties": {
                "appointment_id": {
                    "type": "integer",
                    "description": "ID of the existing appointment"
                },
                "new_date": {
                    "type": "string",
                    "description": "New appointment date in YYYY-MM-DD format"
                },
                "new_time": {
                    "type": "string",
                    "description": "New appointment time in HH:MM format"
                },
                "new_doctor_id": {
                    "type": "integer",
                    "description": "Optional ID of the new doctor if changing doctor"
                },
                "new_service_id": {
                    "type": "integer",
                    "description": "Optional ID of the new service if changing service"
                }
            },
            "required": ["appointment_id", "new_date", "new_time"]
        }
    },
    {
        "name": "update_customer_details",
        "description": "Update or correct the patient/customer's stored contact details (name and/or phone number) without cancelling, rescheduling, or altering their booked appointments.",
        "parameters": {
            "type": "object",
            "properties": {
                "customer_name": {
                    "type": "string",
                    "description": "New or corrected full name of the customer (optional)"
                },
                "customer_phone": {
                    "type": "string",
                    "description": "New or corrected contact phone number of the customer (optional)"
                }
            },
            "required": []
        }
    },
    {
        "name": "human_handoff",
        "description": "Transfer the conversation to a human clinic receptionist when requested by the customer or when encountering unknown/unsupported queries or requests for medical advice.",
        "parameters": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "description": "Detailed reason for transferring to human staff"
                }
            },
            "required": ["reason"]
        }
    }
]


class ToolDispatcher:
    def __init__(self, business_id: int, conversation_id: int):
        self.business_id = business_id
        self.conversation_id = conversation_id

    def execute(self, tool_name: str, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Dispatch tool call to corresponding backend business service."""
        try:
            if tool_name == "get_clinic_info":
                return BookingService.get_clinic_info(self.business_id)

            elif tool_name == "get_services":
                doc_id_raw = arguments.get("doctor_id")
                try:
                    parsed_doc_id = int(doc_id_raw) if doc_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_doc_id = None
                if not parsed_doc_id:
                    return {"services": [], "error": "doctor_id parameter is required to retrieve services."}
                return {"services": BookingService.get_services(self.business_id, doctor_id=parsed_doc_id)}

            elif tool_name == "get_doctors":
                return {"doctors": BookingService.get_doctors(self.business_id)}

            elif tool_name == "check_availability":
                date_str = arguments.get("date")
                doctor_id = arguments.get("doctor_id")
                service_id = arguments.get("service_id")
                if doctor_id:
                    try:
                        doctor_id = int(doctor_id)
                    except (ValueError, TypeError):
                        doctor_id = None
                if service_id:
                    try:
                        service_id = int(service_id)
                    except (ValueError, TypeError):
                        service_id = None
                return BookingService.check_availability(
                    business_id=self.business_id,
                    doctor_id=doctor_id,
                    service_id=service_id,
                    date_str=date_str
                )

            elif tool_name == "book_appointment":
                from models import db, Conversation
                conv = db.session.get(Conversation, self.conversation_id) if self.conversation_id else None

                doc_id_raw = arguments.get("doctor_id") or (conv.selected_doctor_id if conv else None)
                svc_id_raw = arguments.get("service_id") or (conv.selected_service_id if conv else None)
                try:
                    parsed_doc_id = int(doc_id_raw) if doc_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_doc_id = None
                try:
                    parsed_svc_id = int(svc_id_raw) if svc_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_svc_id = None

                booked_by = None
                if conv and conv.visitor_id and "wa_" in conv.visitor_id:
                    booked_by = conv.visitor_id.replace("wa_", "").replace("whatsapp_", "")
                elif conv and conv.customer and conv.customer.phone:
                    booked_by = conv.customer.phone

                cust_phone = (
                    arguments.get("customer_phone")
                    or arguments.get("phone")
                    or arguments.get("phone_number")
                    or arguments.get("patient_phone")
                    or arguments.get("contact_number")
                    or (conv.pending_customer_phone if conv else None)
                    or (conv.customer.phone if (conv and conv.customer) else None)
                    or (booked_by if (booked_by and len(booked_by) >= 7) else "")
                    or ""
                )

                cust_name = (
                    arguments.get("customer_name")
                    or arguments.get("patient_name")
                    or arguments.get("name")
                    or (conv.pending_customer_name if conv else None)
                    or (conv.customer.name if (conv and conv.customer) else None)
                    or ""
                )

                appt_date = (
                    arguments.get("appointment_date")
                    or arguments.get("date")
                    or (conv.requested_date if conv else "")
                    or ""
                )
                appt_time = (
                    arguments.get("appointment_time")
                    or arguments.get("time")
                    or (conv.requested_time if conv else "")
                    or ""
                )

                return BookingService.book_appointment(
                    business_id=self.business_id,
                    customer_name=str(cust_name).strip(),
                    customer_phone=str(cust_phone).strip(),
                    doctor_id=parsed_doc_id,
                    service_id=parsed_svc_id,
                    appointment_date=str(appt_date).strip(),
                    appointment_time=str(appt_time).strip(),
                    notes=arguments.get("notes"),
                    idempotency_key=arguments.get("idempotency_key"),
                    conversation_id=self.conversation_id,
                    booked_by_phone=booked_by
                )

            elif tool_name == "get_appointment_details":
                appt_id_raw = arguments.get("appointment_id")
                try:
                    parsed_appt_id = int(appt_id_raw) if appt_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_appt_id = None
                phone = arguments.get("customer_phone")
                cid = None
                booked_by = None
                from models import db, Conversation
                conv = db.session.get(Conversation, self.conversation_id) if self.conversation_id else None
                if conv:
                    if not phone:
                        phone = conv.pending_customer_phone or (conv.customer.phone if conv.customer else None)
                    cid = conv.customer_id
                    if conv.visitor_id and "wa_" in conv.visitor_id:
                        booked_by = conv.visitor_id.replace("wa_", "").replace("whatsapp_", "")

                # If no appointment_id in arguments, check recent messages for appointment id patterns (e.g. 'Id 1 thi', 'Id # 2', '#2')
                if not parsed_appt_id and conv and conv.messages:
                    for m in reversed(conv.messages[-4:]):
                        if m.role == "user":
                            match = re.search(r'\b(?:id|#|appointment|booking)\s*[:#]?\s*(\d+)\b', m.content, re.IGNORECASE)
                            if match:
                                try:
                                    parsed_appt_id = int(match.group(1))
                                    break
                                except Exception:
                                    pass

                return BookingService.get_appointment_details(
                    business_id=self.business_id,
                    appointment_id=parsed_appt_id,
                    customer_phone=phone,
                    customer_id=cid,
                    conversation_id=self.conversation_id,
                    booked_by_phone=booked_by
                )

            elif tool_name == "cancel_appointment":
                appt_id_raw = arguments.get("appointment_id")
                try:
                    parsed_appt_id = int(appt_id_raw) if appt_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_appt_id = None
                if not parsed_appt_id:
                    return {"success": False, "error": "Valid appointment_id is required."}
                return BookingService.cancel_appointment(
                    business_id=self.business_id,
                    appointment_id=parsed_appt_id,
                    reason=arguments.get("reason")
                )

            elif tool_name == "reschedule_appointment":
                appt_id_raw = arguments.get("appointment_id")
                try:
                    parsed_appt_id = int(appt_id_raw) if appt_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_appt_id = None
                if not parsed_appt_id:
                    return {"success": False, "error": "Valid appointment_id is required."}
                new_doc_id_raw = arguments.get("new_doctor_id")
                try:
                    parsed_new_doc_id = int(new_doc_id_raw) if new_doc_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_new_doc_id = None
                new_svc_id_raw = arguments.get("new_service_id")
                try:
                    parsed_new_svc_id = int(new_svc_id_raw) if new_svc_id_raw is not None else None
                except (ValueError, TypeError):
                    parsed_new_svc_id = None
                return BookingService.reschedule_appointment(
                    business_id=self.business_id,
                    appointment_id=parsed_appt_id,
                    new_date=arguments.get("new_date", ""),
                    new_time=arguments.get("new_time", ""),
                    new_doctor_id=parsed_new_doc_id,
                    new_service_id=parsed_new_svc_id
                )

            elif tool_name == "update_customer_details":
                return BookingService.update_customer_details(
                    business_id=self.business_id,
                    conversation_id=self.conversation_id,
                    customer_name=arguments.get("customer_name"),
                    customer_phone=arguments.get("customer_phone")
                )

            elif tool_name == "human_handoff":
                return HandoffService.trigger_handoff(
                    conversation_id=self.conversation_id,
                    reason=arguments.get("reason", "Customer requested human assistance"),
                    business_id=self.business_id
                )

            else:
                return {"error": f"Unknown tool: {tool_name}"}

        except Exception as e:
            return {"error": f"Failed executing tool '{tool_name}': {str(e)}"}
